// src/solid/components/TweakRoot.tsx
import { createSignal, onMount, onCleanup, Show, For } from 'solid-js';
import { Portal } from 'solid-js/web';
import { TweakStore } from '../../store/TweakStore';
import type { PanelConfig } from '../../store/TweakStore';
import { TimelineStore } from '../../store/TimelineStore';
import { ShortcutListener } from './ShortcutListener';
import { Panel } from './Panel';
import { Folder } from './Folder';
import { TimelineToggleButton } from './Timeline/TimelineToggleButton';

export type TweakPosition = 'top-right' | 'top-left' | 'bottom-right' | 'bottom-left';
export type TweakMode = 'popover' | 'inline';
/** `card` is the panel's glass surface; `none` puts the rows straight on the host's ground. */
export type TweakChrome = 'card' | 'none';
export type TweakTheme = 'light' | 'dark' | 'system';

declare const process: { env?: { NODE_ENV?: string } } | undefined;

const isDevDefault = typeof process !== 'undefined' && process?.env?.NODE_ENV
  ? process.env.NODE_ENV !== 'production'
  : typeof import.meta !== 'undefined' && (import.meta as any).env?.MODE
    ? (import.meta as any).env.MODE !== 'production'
    : true;

interface TweakRootProps {
  position?: TweakPosition;
  defaultOpen?: boolean;
  mode?: TweakMode;
  theme?: TweakTheme;
  productionEnabled?: boolean;
  /**
   * Render only the named panels, in the order given. For apps that place
   * more than one panel surface in more than one place — a rack of per-voice
   * columns beside a global panel, say. Omitted, a root renders every
   * registered panel, which is the single-surface default.
   */
  panels?: string | string[];
  /**
   * `none` drops the panel card — no glass, no border, no radius, no padding —
   * so the rows sit directly on the host's own surface. For app chrome that
   * already provides the ground the panel would otherwise float on.
   */
  chrome?: TweakChrome;
}

export function TweakRoot(props: TweakRootProps) {
  if ((props.productionEnabled ?? isDevDefault) === false) return null;
  const [panels, setPanels] = createSignal<PanelConfig[]>([]);
  const [timelineCount, setTimelineCount] = createSignal(0);
  const [mounted, setMounted] = createSignal(false);
  const inline = () => (props.mode ?? 'popover') === 'inline';

  const read = () => TweakStore.selectPanels(props.panels);

  onMount(() => {
    setMounted(true);
    setPanels(read());
    setTimelineCount(TimelineStore.getTimelines().length);
    const unsubPanels = TweakStore.subscribeGlobal(() => {
      setPanels(read());
    });
    const unsubTimelines = TimelineStore.subscribeGlobal(() => {
      setTimelineCount(TimelineStore.getTimelines().length);
    });
    onCleanup(() => {
      unsubPanels();
      unsubTimelines();
    });
  });

  // Timeline-backed panels render in TweakTimeline, but their presence adds a
  // visibility toggle to the dock toolbar here.
  const timelineToggle = () =>
    timelineCount() > 0 && props.panels === undefined ? <TimelineToggleButton /> : null;

  const content = () => (
    <ShortcutListener>
      <div class="tweakers-root" data-mode={props.mode ?? 'popover'} data-theme={props.theme ?? 'system'} data-chrome={props.chrome ?? 'card'}>
        <div class="tweakers-panel" data-position={inline() ? undefined : (props.position ?? 'top-right')} data-mode={props.mode ?? 'popover'}>
          <Show
            when={panels().length > 0}
            fallback={
              <div class="tweakers-panel-wrapper">
                <Folder
                  title="Tweakers"
                  defaultOpen={inline() || (props.defaultOpen ?? true)}
                  isRoot={true}
                  inline={inline()}
                  toolbar={timelineToggle()}
                >
                  <div class="tweakers-timeline-toolkit-only">Timeline</div>
                </Folder>
              </div>
            }
          >
            <For each={panels()}>
              {(panel) => (
                <Panel
                  panel={panel}
                  defaultOpen={inline() || (props.defaultOpen ?? true)}
                  inline={inline()}
                  toolbarExtra={timelineToggle()}
                />
              )}
            </For>
          </Show>
        </div>
      </div>
    </ShortcutListener>
  );

  return (
    <Show
      when={
        mounted() &&
        typeof window !== 'undefined' &&
        (panels().length > 0 || (props.panels === undefined && timelineCount() > 0))
      }
    >
      <Show when={!inline()} fallback={content()}>
        <Portal mount={document.body}>
          {content()}
        </Portal>
      </Show>
    </Show>
  );
}

// src/svelte/components/TweakRoot.svelte
<script lang="ts">
  import { TweakStore } from 'tweakers/store';
  import type { PanelConfig } from 'tweakers/store';
  import { TimelineStore, isDevDefault } from 'tweakers/timeline';
  import { themeCSS } from '../theme-css';
  import Portal from '../Portal.svelte';
  import Panel from './Panel.svelte';
  import Folder from './Folder.svelte';
  import ShortcutListener from './ShortcutListener.svelte';
  import TimelineToggleButton from './Timeline/TimelineToggleButton.svelte';

  export type TweakPosition = 'top-right' | 'top-left' | 'bottom-right' | 'bottom-left';
  export type TweakMode = 'popover' | 'inline';
  /** `card` is the panel's glass surface; `none` puts the rows straight on the host's ground. */
  export type TweakChrome = 'card' | 'none';
  export type TweakTheme = 'light' | 'dark' | 'system';

  let { position = 'top-right', defaultOpen = true, mode = 'popover', theme = 'system' as TweakTheme, productionEnabled = isDevDefault, panels: only = undefined, chrome = 'card' } = $props<{
    position?: TweakPosition;
    defaultOpen?: boolean;
    mode?: TweakMode;
    theme?: TweakTheme;
    productionEnabled?: boolean;
    /**
     * Render only the named panels, in the order given. For apps that place
     * more than one panel surface in more than one place — a rack of per-voice
     * columns beside a global panel, say. Omitted, a root renders every
     * registered panel, which is the single-surface default.
     */
    panels?: string | string[];
    /**
     * `none` drops the panel card — no glass, no border, no radius, no padding —
     * so the rows sit directly on the host's own surface. For app chrome that
     * already provides the ground the panel would otherwise float on.
     */
    chrome?: TweakChrome;
  }>();

  const inline = $derived(mode === 'inline');

  let panels = $state<PanelConfig[]>([]);
  let timelineCount = $state(0);
  let mounted = $state(false);

  $effect(() => {
    if (typeof document === 'undefined') return;
    const id = 'tweakers-theme';
    if (!document.getElementById(id)) {
      const style = document.createElement('style');
      style.id = id;
      style.textContent = themeCSS;
      document.head.appendChild(style);
    }
  });

  $effect(() => {
    if (typeof window === 'undefined') return;

    mounted = true;
    panels = TweakStore.selectPanels(only);
    timelineCount = TimelineStore.getTimelines().length;

    const unsubPanels = TweakStore.subscribeGlobal(() => {
      panels = TweakStore.selectPanels(only);
    });
    const unsubTimelines = TimelineStore.subscribeGlobal(() => {
      timelineCount = TimelineStore.getTimelines().length;
    });

    return () => {
      unsubPanels();
      unsubTimelines();
    };
  });
</script>

{#if productionEnabled && mounted && (panels.length > 0 || (only === undefined && timelineCount > 0))}
  <!-- Timeline-backed panels render in TweakTimeline; their presence only adds a
       visibility toggle to the dock toolbar here. -->
  {#snippet timelineToggle()}
    {#if timelineCount > 0 && only === undefined}
      <TimelineToggleButton />
    {/if}
  {/snippet}

  {#snippet content()}
    <ShortcutListener>
      <div class="tweakers-root" data-mode={mode} data-theme={theme} data-chrome={chrome}>
        <div class="tweakers-panel" data-mode={mode} data-position={inline ? undefined : position}>
          {#if panels.length > 0}
            {#each panels as panel (panel.id)}
              <Panel {panel} defaultOpen={inline || defaultOpen} {inline} toolbarExtra={timelineToggle} />
            {/each}
          {:else}
            <div class="tweakers-panel-wrapper">
              <Folder title="Tweakers" defaultOpen={inline || defaultOpen} isRoot={true} {inline} toolbar={timelineToggle}>
                <div class="tweakers-timeline-toolkit-only">Timeline</div>
              </Folder>
            </div>
          {/if}
        </div>
      </div>
    </ShortcutListener>
  {/snippet}

  {#if inline}
    {@render content()}
  {:else}
    <Portal target="body">
      {@render content()}
    </Portal>
  {/if}
{/if}
