// src/solid/components/Panel.tsx
import { createSignal, createEffect, onMount, onCleanup, JSX } from 'solid-js';
import { animate } from 'motion';
import { ICON_CLIPBOARD, ICON_CHECK, ICON_ADD_PRESET } from '../../icons';
import { TweakStore } from '../../store/TweakStore';
import type { PanelConfig, TweakValue } from '../../store/TweakStore';
import { Folder } from './Folder';
import { ControlRenderer } from './ControlRenderer';
import { PresetManager } from './PresetManager';

interface PanelProps {
  panel: PanelConfig;
  defaultOpen?: boolean;
  inline?: boolean;
  toolbarExtra?: JSX.Element;
}

export function Panel(props: PanelProps) {
  const [copied, setCopied] = createSignal(false);
  const [, setIsPanelOpen] = createSignal(props.defaultOpen ?? true);
  const [values, setValues] = createSignal<Record<string, TweakValue>>(
    TweakStore.getValues(props.panel.id)
  );
  const [presets, setPresets] = createSignal(TweakStore.getPresetItems(props.panel.id));
  const [activePresetId, setActivePresetId] = createSignal(TweakStore.getActivePresetId(props.panel.id));
  const [providerMode, setProviderMode] = createSignal(TweakStore.hasPresetProvider(props.panel.id));
  let addButtonRef!: HTMLButtonElement;
  let copyButtonRef!: HTMLButtonElement;
  let copyClipboardIconRef!: HTMLSpanElement;
  let copyCheckIconRef!: HTMLSpanElement;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  let addTapAnim: any = null;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  let copyTapAnim: any = null;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  let copyClipboardAnim: any = null;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  let copyCheckAnim: any = null;
  let didInitCopyIcons = false;

  const tapTransition = { type: 'spring' as const, visualDuration: 0.15, bounce: 0.3 };

  onMount(() => {
    const unsub = TweakStore.subscribe(props.panel.id, () => {
      setValues(TweakStore.getValues(props.panel.id));
      setPresets(TweakStore.getPresetItems(props.panel.id));
      setActivePresetId(TweakStore.getActivePresetId(props.panel.id));
      setProviderMode(TweakStore.hasPresetProvider(props.panel.id));
    });

    if (copyClipboardIconRef && copyCheckIconRef) {
      copyClipboardIconRef.style.transformOrigin = '50% 50%';
      copyClipboardIconRef.style.opacity = '1';
      copyClipboardIconRef.style.transform = 'scale(1)';
      copyClipboardIconRef.style.filter = 'blur(0px)';
      copyCheckIconRef.style.transformOrigin = '50% 50%';
      copyCheckIconRef.style.opacity = '0';
      copyCheckIconRef.style.transform = 'scale(0.5)';
      copyCheckIconRef.style.filter = 'blur(4px)';
      didInitCopyIcons = true;
    }

    onCleanup(unsub);
  });

  const handleAddPreset = () => TweakStore.createPreset(props.panel.id);

  const handleCopy = () => {
    const jsonStr = JSON.stringify(values(), null, 2);
    const instruction = `Update the createTweakers configuration for "${props.panel.name}" with these values:\n\n\`\`\`json\n${jsonStr}\n\`\`\`\n\nApply these values as the new defaults in the createTweakers call.`;
    navigator.clipboard.writeText(instruction);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  };

  createEffect(() => {
    const isCopied = copied();
    if (!copyClipboardIconRef || !copyCheckIconRef) return;

    copyClipboardAnim?.stop();
    copyCheckAnim?.stop();

    if (!didInitCopyIcons) return;

    const transition = { type: 'spring' as const, visualDuration: 0.3, bounce: 0.2 };
    copyClipboardAnim = animate(copyClipboardIconRef, {
      opacity: isCopied ? 0 : 1,
      scale: isCopied ? 0.5 : 1,
      filter: isCopied ? 'blur(4px)' : 'blur(0px)',
    }, transition);
    copyCheckAnim = animate(copyCheckIconRef, {
      opacity: isCopied ? 1 : 0,
      scale: isCopied ? 1 : 0.5,
      filter: isCopied ? 'blur(0px)' : 'blur(4px)',
    }, transition);
  });

  onCleanup(() => {
    addTapAnim?.stop();
    copyTapAnim?.stop();
    copyClipboardAnim?.stop();
    copyCheckAnim?.stop();
  });

  const handleAddTapStart = () => {
    if (!addButtonRef) return;
    addTapAnim?.stop();
    addTapAnim = animate(addButtonRef, { scale: 0.9 }, tapTransition);
  };

  const handleAddTapEnd = () => {
    if (!addButtonRef) return;
    addTapAnim?.stop();
    addTapAnim = animate(addButtonRef, { scale: 1 }, tapTransition);
  };

  const handleCopyTapStart = () => {
    if (!copyButtonRef) return;
    copyTapAnim?.stop();
    copyTapAnim = animate(copyButtonRef, { scale: 0.95 }, tapTransition);
  };

  const handleCopyTapEnd = () => {
    if (!copyButtonRef) return;
    copyTapAnim?.stop();
    copyTapAnim = animate(copyButtonRef, { scale: 1 }, tapTransition);
  };

  const renderControls = () => (
    <ControlRenderer panelId={props.panel.id} controls={props.panel.controls} values={values()} />
  );

  const presetsHidden = () => TweakStore.arePresetsHidden(props.panel.id);

  const toolbar = presetsHidden() ? props.toolbarExtra : (
    <>
      <button
        ref={addButtonRef}
        class="tweakers-toolbar-add"
        onClick={handleAddPreset}
        onPointerDown={handleAddTapStart}
        onPointerUp={handleAddTapEnd}
        onPointerCancel={handleAddTapEnd}
        onPointerLeave={handleAddTapEnd}
        title="Add preset"
      >
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round">
          <path d={ICON_ADD_PRESET[0]} />
          <path d={ICON_ADD_PRESET[1]} />
          <path d={ICON_ADD_PRESET[2]} />
          <path d={ICON_ADD_PRESET[3]} />
          <path d={ICON_ADD_PRESET[4]} />
        </svg>
      </button>

      <PresetManager
        panelId={props.panel.id}
        presets={presets()}
        activePresetId={activePresetId()}
        onAdd={handleAddPreset}
        providerMode={providerMode()}
      />

      <button
        ref={copyButtonRef}
        class="tweakers-toolbar-copy"
        onClick={handleCopy}
        onPointerDown={handleCopyTapStart}
        onPointerUp={handleCopyTapEnd}
        onPointerCancel={handleCopyTapEnd}
        onPointerLeave={handleCopyTapEnd}
        title="Copy parameters"
      >
        <span class="tweakers-toolbar-copy-icon-wrap">
          <span
            ref={copyClipboardIconRef}
            class="tweakers-toolbar-copy-icon"
            style={{ opacity: 1, transform: 'scale(1)', filter: 'blur(0px)' }}
          >
            <svg viewBox="0 0 24 24" fill="none" width="16" height="16">
              <path d={ICON_CLIPBOARD.board} stroke="currentColor" stroke-width="2" stroke-linejoin="round" />
              <path d={ICON_CLIPBOARD.sparkle} fill="currentColor" />
              <path d={ICON_CLIPBOARD.body} stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
            </svg>
          </span>
          <span
            ref={copyCheckIconRef}
            class="tweakers-toolbar-copy-icon"
            style={{ opacity: 0, transform: 'scale(0.5)', filter: 'blur(4px)' }}
          >
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" width="16" height="16">
              <path d={ICON_CHECK} />
            </svg>
          </span>
        </span>
      </button>

      {props.toolbarExtra}
    </>
  );

  return (
    <div class="tweakers-panel-wrapper">
      <Folder
        title={props.panel.name}
        defaultOpen={props.defaultOpen ?? true}
        isRoot={true}
        inline={props.inline ?? false}
        onOpenChange={setIsPanelOpen}
        toolbar={toolbar}
        enabled={props.panel.module ? (values()['_enabled'] as boolean) : undefined}
        onEnabledChange={
          props.panel.module
            ? (v) => TweakStore.updateValue(props.panel.id, '_enabled', v)
            : undefined
        }
      >
        {renderControls()}
      </Folder>
    </div>
  );
}

// src/components/Panel.tsx
import { useState, useSyncExternalStore } from 'react';
import type { ReactNode } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { TweakStore, PanelConfig, ControlMeta, TAB_PATH } from '../store/TweakStore';
import { splitPanelTabs } from '../panel-tabs';
import { buildCopyInstruction } from '../copy-instruction';
import { ICON_CLIPBOARD, ICON_CHECK, ICON_ADD_PRESET } from '../icons';
import { Folder } from './Folder';
import { ControlRenderer } from './ControlRenderer';
import { PresetManager } from './PresetManager';
import { SegmentedControl } from './SegmentedControl';

interface PanelProps {
  panel: PanelConfig;
  defaultOpen?: boolean;
  inline?: boolean;
  toolbarExtra?: ReactNode;
}

export function Panel({ panel, defaultOpen = true, inline = false, toolbarExtra }: PanelProps) {
  const [copied, setCopied] = useState(false);
  const [, setIsPanelOpen] = useState(defaultOpen);

  // Subscribe to panel value changes
  const values = useSyncExternalStore(
    (cb) => TweakStore.subscribe(panel.id, cb),
    () => TweakStore.getValues(panel.id),
    () => TweakStore.getValues(panel.id)
  );

  const presets = TweakStore.getPresetItems(panel.id);
  const activePresetId = TweakStore.getActivePresetId(panel.id);
  const providerMode = TweakStore.hasPresetProvider(panel.id);

  // Bumped per add: the preset manager opens and puts the fresh preset's
  // name straight into inline edit.
  const [presetEditSignal, setPresetEditSignal] = useState(0);
  const handleAddPreset = () => {
    TweakStore.createPreset(panel.id);
    setPresetEditSignal((n) => n + 1);
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(buildCopyInstruction('useTweakers', panel.name, values));
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  };

  const { tabs, activeTab, looseControls, pageControls } = splitPanelTabs(panel.controls, values[TAB_PATH]);

  const tabBar = activeTab ? (
    <SegmentedControl
      options={tabs.map((tab) => ({ value: tab.path, label: tab.label }))}
      value={activeTab.path}
      onChange={(v) => TweakStore.updateValue(panel.id, TAB_PATH, v)}
    />
  ) : undefined;

  const renderRows = (controls: ControlMeta[]) => (
    <ControlRenderer panelId={panel.id} controls={controls} values={values} />
  );

  // The page is keyed by tab so switching swaps it outright, rather than
  // reconciling one tab's rows into the next tab's.
  const renderControls = () =>
    activeTab ? (
      <>
        {renderRows(looseControls)}
        <div key={activeTab.path} className="tweakers-panel-tab-page">
          {renderRows(pageControls)}
        </div>
      </>
    ) : (
      renderRows(pageControls)
    );

  const presetsHidden = TweakStore.arePresetsHidden(panel.id);

  const toolbar = presetsHidden ? toolbarExtra : (
    <>
      <motion.button
        className="tweakers-toolbar-add"
        onClick={handleAddPreset}
        title="Add preset"
        whileTap={{ scale: 0.9 }}
        transition={{ type: 'spring', visualDuration: 0.15, bounce: 0.3 }}
      >
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
          {ICON_ADD_PRESET.map((d, i) => (
            <path key={i} d={d} />
          ))}
        </svg>
      </motion.button>

      <PresetManager
        panelId={panel.id}
        presets={presets}
        activePresetId={activePresetId}
        onAdd={handleAddPreset}
        providerMode={providerMode}
        editSignal={presetEditSignal}
      />

      <motion.button
        className="tweakers-toolbar-add"
        onClick={handleCopy}
        title="Copy parameters"
        whileTap={{ scale: 0.9 }}
        transition={{ type: 'spring', visualDuration: 0.15, bounce: 0.3 }}
      >
        <span style={{ position: 'relative', width: 14, height: 14 }}>
          <AnimatePresence initial={false} mode="wait">
            {copied ? (
              <motion.svg
                key="check"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
                style={{ position: 'absolute', inset: 0, width: 14, height: 14, color: 'var(--tweak-text-label)' }}
                initial={{ scale: 0.8, opacity: 0 }}
                animate={{ scale: 1, opacity: 1 }}
                exit={{ scale: 0.8, opacity: 0 }}
                transition={{ duration: 0.08 }}
              >
                <path d={ICON_CHECK} />
              </motion.svg>
            ) : (
              <motion.svg
                key="clipboard"
                viewBox="0 0 24 24"
                fill="none"
                style={{ position: 'absolute', inset: 0, width: 14, height: 14, color: 'var(--tweak-text-label)' }}
                initial={{ scale: 0.8, opacity: 0 }}
                animate={{ scale: 1, opacity: 1 }}
                exit={{ scale: 0.8, opacity: 0 }}
                transition={{ duration: 0.08 }}
              >
                <path d={ICON_CLIPBOARD.board} stroke="currentColor" strokeWidth="2" strokeLinejoin="round"/>
                <path d={ICON_CLIPBOARD.sparkle} fill="currentColor"/>
                <path d={ICON_CLIPBOARD.body} stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
              </motion.svg>
            )}
          </AnimatePresence>
        </span>
      </motion.button>

      {toolbarExtra}
    </>
  );

  return (
    <div className="tweakers-panel-wrapper">
      <Folder
        title={panel.name}
        defaultOpen={defaultOpen}
        isRoot={true}
        inline={inline}
        onOpenChange={setIsPanelOpen}
        toolbar={toolbar}
        tabs={tabBar}
        enabled={panel.module ? (values['_enabled'] as boolean) : undefined}
        onEnabledChange={
          panel.module ? (v) => TweakStore.updateValue(panel.id, '_enabled', v) : undefined
        }
      >
        {renderControls()}
      </Folder>
    </div>
  );
}
